---
title: "Pancreatic tumor"
output: html_document
date: "2026-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# create directories

dir.create("../xlsx", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../xlsx/surg", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../xlsx/surg/dem", showWarnings = TRUE, recursive = FALSE, mode = "0777")
dir.create("../xlsx/surg/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")
dir.create("../xlsx/surg/mon", showWarnings = TRUE, recursive = FALSE, mode = "0777")
dir.create("../xlsx/surg/sec", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


```{r}
# h26 age
# https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000140360.xlsx

# h27 age
# https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000177266.xlsx

# h28
# https://www.mhlw.go.jp/content/12400000/000347727.xlsx

# h29 
# https://www.mhlw.go.jp/content/12400000/000711858.xlsx

# h30
# https://www.mhlw.go.jp/content/12400000/000539726.xlsx

# h31
# https://www.mhlw.go.jp/content/12400000/000821487.xlsx

# r2
# https://www.mhlw.go.jp/content/12400000/001262185.xlsx

# r3
# https://www.mhlw.go.jp/content/12400000/001122125.xlsx

# r4
# https://www.mhlw.go.jp/content/12400000/001258346.xlsx

# r5
# https://www.mhlw.go.jp/content/12400000/001493186.xlsx

url_dem <- c(
  "https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000140360.xlsx",
  "https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000177266.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000347727.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000711858.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000539726.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000821487.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001262185.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001122125.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001258346.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001493186.xlsx")
```

```{r}
file_dem <- url_dem %>% str_extract("00[:digit:]+\\.xlsx")

path_dem <- paste0("../xlsx/surg/dem/", file_dem)
```

```{r}
for (i in 1:length(url_dem)){
  download.file(url_dem[i], path_dem[i], mode = "wb")
  print(paste(file_dem[i], "downloaded"))
}
```


```{r}
# h26 pref
# https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000140361.xlsx

# h27 pref
# https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000177267.xlsx

# h28
# https://www.mhlw.go.jp/content/12400000/000347728.xlsx

# h29
# https://www.mhlw.go.jp/content/12400000/000711860.xlsx

# h30
# https://www.mhlw.go.jp/content/12400000/000539727.xlsx

# h31
# https://www.mhlw.go.jp/content/12400000/000821489.xlsx

# r2
# https://www.mhlw.go.jp/content/12400000/001262186.xlsx

# r3
# https://www.mhlw.go.jp/content/12400000/001122126.xlsx

# r4
# https://www.mhlw.go.jp/content/12400000/001258347.xlsx

# r5
# https://www.mhlw.go.jp/content/12400000/001493188.xlsx

url_prf <- c(
  "https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000140361.xlsx",
  "https://www.mhlw.go.jp/file/06-Seisakujouhou-12400000-Hokenkyoku/0000177267.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000347728.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000711860.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000539727.xlsx",
  "https://www.mhlw.go.jp/content/12400000/000821489.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001262186.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001258347.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001122126.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001493188.xlsx"
)
```

```{r}
file_prf <- url_prf %>% str_extract("00[:digit:]+\\.xlsx")

path_prf <- paste0("../xlsx/surg/prf/", file_prf)
```

```{r}
for (i in 1:length(url_prf)){
  download.file(url_prf[i], path_prf[i], mode = "wb")
  print(paste(file_prf[i], "downloaded"))
}
```

```{r}
# monthly

# h31
# https://www.mhlw.go.jp/content/12400000/000821486.xlsx

# r2
# https://www.mhlw.go.jp/content/12400000/001262187.xlsx

# r3
# https://www.mhlw.go.jp/content/12400000/001122127.xlsx

# r4
# https://www.mhlw.go.jp/content/12400000/001258348.xlsx

# r5
# https://www.mhlw.go.jp/content/12400000/001493190.xlsx


url_mon <- c(
  "https://www.mhlw.go.jp/content/12400000/000821486.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001262187.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001122127.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001258348.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001493190.xlsx"
)

```

```{r}
file_mon <- url_mon %>% str_extract("00[:digit:]+\\.xlsx")

path_mon <- paste0("../xlsx/surg/mon/", file_mon)
```


```{r}
for (i in 1:length(url_mon)){
  download.file(url_mon[i], path_mon[i], mode = "wb")
  print(paste(file_mon[i], "downloaded"))
}
```

```{r}
# secondary

# h31
# https://www.mhlw.go.jp/content/12400000/000821490.xlsx

# r2
# https://www.mhlw.go.jp/content/12400000/001262188.xlsx

# r3
# https://www.mhlw.go.jp/content/12400000/001122128.xlsx

# r4
# https://www.mhlw.go.jp/content/12400000/001258349.xlsx

# r5
# https://www.mhlw.go.jp/content/12400000/001493192.xlsx

url_sec <- c(
  "https://www.mhlw.go.jp/content/12400000/000821490.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001262188.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001122128.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001258349.xlsx",
  "https://www.mhlw.go.jp/content/12400000/001493192.xlsx"
)
```

```{r}
file_sec <- url_sec %>% str_extract("00[:digit:]+\\.xlsx")

path_sec <- paste0("../xlsx/surg/sec/", file_sec)
```

```{r}
for (i in 1:length(url_sec)){
  download.file(url_sec[i], path_sec[i], mode = "wb")
  print(paste(file_sec[i], "downloaded"))
}
```
