---
title: "Pancreatic tumor"
output: html_document
date: "2026-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(sf)
library(rnaturalearth)
```



```{r}
list.files("../xlsx/test/sec")
```

```{r}
df_inj_sec_reg <- readRDS("../rds/inj/sec/df_inj_sec_reg")

df_test_sec_reg <- readRDS("../rds/test/sec/df_test_sec_reg")

df_surg_sec_reg <- readRDS("../rds/surg/sec/df_surg_sec_reg")
```


```{r}
colnames(df_surg_sec_reg)
```




```{r}
#regular long

df_inj_sec_rl <- df_inj_sec_reg %>%
  pivot_longer(cols = c(starts_with("0"),
                        starts_with("1"),
                        starts_with("2"),
                        starts_with("3"),
                        starts_with("4")),
               names_to = "SEC_jp",
               values_to = "VALUE")
```

```{r}
df_inj_sec_rl %>% head()
```


```{r}
df_inj_sec_rl <-  df_inj_sec_rl %>%
  mutate(SEC_jp_ori = SEC_jp) %>%
  mutate(PRF_no = str_extract(SEC_jp, "^[:digit:]{2}(?=\\_)")) %>%
  mutate(SEC_jp = str_remove(SEC_jp, "^[:digit:]{2}_")) %>%
  mutate(PRF_jp = str_extract(SEC_jp, "^[^\\_]+(?=\\_)")) %>%
  mutate(SEC_jp = str_remove(SEC_jp, "^[^\\_]+\\_")) %>%
  mutate(SEC_no = str_extract(SEC_jp, "^[^\\_]+(?=\\_)")) %>%
  mutate(SEC_jp = str_remove(SEC_jp, "^[^\\_]+\\_")) %>%
  relocate(SEC_jp, .after = "SEC_no")
  
```

```{r}
df_jp <- rnaturalearth::ne_states("japan") %>% 
  as_tibble() %>%
  select(iso_3166_2, name_ja, name_en) %>%
  arrange(iso_3166_2) %>%
  rename(PRF_jp = "name_ja") %>%
  rename(PRF = "name_en") %>%
  mutate(PRF = str_replace_all(PRF, "Ō", "O")) %>%
  mutate(PRF = str_replace_all(PRF, "ō", "o")) %>%
  mutate(PRF = str_remove(PRF, "Prefecture")) %>%
  mutate(PRF = str_trim(PRF, side = "both"))
```


```{r}
#regular long

df_inj_prf_rl <- df_inj_sec_rl %>%
  left_join(df_jp, by = join_by(PRF_jp))
```

```{r}
df_inj_prf_rl
```

```{r}
levels_prf <- df_jp %>% arrange(iso_3166_2) %>% pull(PRF)

levels_prf
```


```{r}
# define region

hokkaido <- c("JP-01")

tohoku <- c(paste0("JP-0", as.character(2:7)))

kanto <- c(paste0("JP-0", as.character(8:9)), 
           paste0("JP-", as.character(10:14)))

chubu <- c(paste0("JP-", as.character(15:24)))

kinki <- c(paste0("JP-", as.character(25:30)))

chugoku <- c(paste0("JP-", as.character(31:35)))

shikoku <- c(paste0("JP-", as.character(36:39)))

kyusyu_okinawa <- c(paste0("JP-", as.character(40:47)))

```


```{r}
levels_reg <- c("Hokkaido",
                "Tohoku",
                "Kanto",
                "Chubu",
                "Kansai",
                "Chugoku",
                "Shikoku",
                "Kyusyu\nOkinawa")
```

```{r}
df_jp <- df_jp %>%
  mutate(REG = case_when(iso_3166_2 %in% hokkaido ~ "Hokkaido",
                         iso_3166_2 %in% tohoku ~ "Tohoku",
                         iso_3166_2 %in% kanto ~ "Kanto",
                         iso_3166_2 %in% chubu ~ "Chubu",
                         iso_3166_2 %in% kinki ~ "Kansai",
                         iso_3166_2 %in% chugoku ~ "Chugoku",
                         iso_3166_2 %in% shikoku ~ "Shikoku",
                         iso_3166_2 %in% kyusyu_okinawa ~ "Kyusyu\nOkinawa")) %>%
  mutate(REG = factor(REG, levels = levels_reg)) %>%
  mutate(PRF = factor(PRF, levels = levels_prf))
```

```{r}
levels_sec <- df_inj_sec_rl %>%
  distinct(SEC_no , SEC_jp) %>%
  arrange(SEC_no) %>% pull(SEC_jp)

head(levels_sec)
```




```{r}
save_sec_long <- function(x){
  df <- x %>%
      pivot_longer(cols = c(starts_with("0"),
                        starts_with("1"),
                        starts_with("2"),
                        starts_with("3"),
                        starts_with("4")),
               names_to = "SEC_jp",
               values_to = "VALUE") %>%
    mutate(SEC_jp_ori = SEC_jp) %>%
    mutate(PRF_no = str_extract(SEC_jp, "^[:digit:]{2}(?=\\_)")) %>%
    mutate(SEC_jp = str_remove(SEC_jp, "^[:digit:]{2}_")) %>%
    mutate(PRF_jp = str_extract(SEC_jp, "^[^\\_]+(?=\\_)")) %>%
    mutate(SEC_jp = str_remove(SEC_jp, "^[^\\_]+\\_")) %>%
    mutate(SEC_no = str_extract(SEC_jp, "^[^\\_]+(?=\\_)")) %>%
    mutate(SEC_jp = str_remove(SEC_jp, "^[^\\_]+\\_")) %>%
    relocate(SEC_jp, .after = "SEC_no") %>%
    left_join(df_jp, by = join_by(PRF_jp)) %>%
    mutate(PRF = factor(PRF, levels = levels_prf)) %>%
    mutate(across(c(TOTAL, VALUE, POINT), ~ na_if(.x, "-"))) %>%
    mutate(across(c(TOTAL, VALUE, POINT), ~ replace_na(.x, "0"))) %>%
    mutate(across(c(TOTAL, VALUE, POINT), ~ as.numeric(.x)))
  
#  levels_sec <- df %>%
#    distinct(SEC_no , SEC_jp) %>%
#    arrange(SEC_no) %>% pull(SEC_jp)
  
#  df <- df %>%
#    mutate(SEC_jp = factor(SEC_jp, levels = levels_sec))
  
  return(df)
}
```


```{r}
df_inj_ps <- df_inj_sec_reg %>% save_sec_long()
```

```{r}
df_inj_ps %>%
  distinct(SEC_no, SEC_jp) %>%
  group_by(SEC_jp) %>%
   filter(n()>1)
```

```{r}
df_inj_ps %>%
    distinct(SEC_no , SEC_jp) %>%
    arrange(SEC_no) %>% pull(SEC_jp)
```


```{r}
type <- c("inj", "test", "surg")

#path <- paste0("../rds/", type, "/dem/df_", type,  "_dem_reg")
```




```{r}
for (i in 1:length(type)){
  from <- paste0("../rds/", type[i], "/sec/df_", type[i],  "_sec_reg")
  
  to <- paste0("../df/sec/df_", type[i], "_sec_reg")
  
  readRDS(from) %>% save_sec_long() %>% saveRDS(to)
}
```

