---
title: "Pancreatic cacner"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(ggtext)
library(ggrepel)
library(ggh4x)

library(patchwork)
library(cowplot)
library(scales)

library(sf)
library(mapdata)

library(dtwclust)
library(rkt)
```


```{r}
# make df folder

dir.create("../plot", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../plot/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../df/rkt", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop_prf <- readRDS("../rds/pop/prf/df_pop_prf")
```

```{r}
df_can_inc_n <- readRDS("../rds/cancer/df_can_inc_number_long.RDS")
```


```{r}
map_jp <-  maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF))
```


# clean

```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(VALUE = replace_na(VALUE, 0))
```


```{r}
df_pop_prf <- df_pop_prf %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", PRF))
```


```{r}
# add region

df_pop_prf <- df_pop_prf %>%
  left_join(df_surg_prf %>% 
              distinct(iso_3166_2, REG),
            by = join_by(iso_3166_2))
```


# pancreas

```{r}
df_surg_prf %>% 
  filter(str_detect(CLASS_code, "^K702|^K703|^K704")) %>%
  count(CLASS_code, CLASS_name, PRO_code, PRO_name)
```


```{r}
df_panc_prf <-  df_surg_prf %>% 
      filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code == "K700" ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Partial")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Partial")))
```

```{r}
# check total

df_surg_prf %>%
  filter(str_detect(CLASS_code, "^K704"))  %>%
  group_by(YEAR) %>%
  summarise(VALUE = sum(VALUE)) %>%
  left_join(df_surg_prf %>%
              filter(str_detect(CLASS_code, "^K704"))  %>%
              distinct(PRO_name, YEAR, .keep_all = TRUE) %>%
              select(YEAR, TOTAL),
            by = join_by(YEAR)) %>%
  mutate(DIF = (VALUE- TOTAL)/TOTAL * 100 )
```



```{r}
df_panc_prf %>%
  filter(YEAR == "2023") %>%
  group_by(YEAR, PRO_name) %>%
  summarise(SUM = sum(VALUE)) %>%
  ungroup() %>%
  left_join(df_panc_prf %>%
              filter(YEAR == "2023") %>%
              distinct(YEAR, PRO_name, .keep_all = TRUE) %>%
              select(PRO_name, TOTAL),
            by = join_by(PRO_name)) %>%
  summarise(SUM = sum(SUM),
            TOTAL = sum(TOTAL)) 
```

```{r}
df_panc_total <- df_panc_prf %>%
  distinct(YEAR, PRO_name, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM_total = sum(TOTAL))

df_panc_total
```

```{r}
df_panc_value <- df_panc_prf %>%
  group_by(YEAR) %>%
  summarise(SUM_value = sum(VALUE))

df_panc_value
```


# what is the source of decline in 2017?

```{r}
df_panc_total_2017 <- df_panc_prf %>%
  filter(YEAR == "2017") %>%
  group_by(PRO_code, PRO_name) %>%
  summarise(SUM_value = sum(VALUE)) %>%
  left_join(df_panc_prf %>%
              filter(YEAR == "2017") %>%
              ungroup() %>%
              distinct(PRO_code, SHEET, .keep_all = TRUE) %>%
              select(PRO_code, TOTAL),
            by = join_by(PRO_code))
  
```

```{r}
df_panc_prf %>%
  filter(YEAR == "2017" & PRO_code == "150296910") %>% 
  select(SHEET, PRO_name, TOTAL, VALUE) %>% View()
```


```{r}
df_panc_total_2017 %>%
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Disal",
                         str_detect(PRO_name, "膵全摘") ~ "Total")) %>%
  group_by(LOC) %>%
  summarise(SUM_value = sum(SUM_value),
            SUM_total = sum(TOTAL))
```


```{r}
df_panc_total %>%
  left_join(df_panc_value,
            by = join_by(YEAR)) %>%
  mutate(PCT = (SUM_value - SUM_total)/SUM_total * 100)
```

```{r}
df_panc_prf_loc <- df_panc_prf %>%
  filter(!LOC %in% c("Middle", "Partial") ) %>%
  group_by(YEAR, LOC, iso_3166_2, PRF) %>%
  summarise(SUM = sum(VALUE)) %>%
  bind_rows(df_panc_prf %>%
              group_by(YEAR, PRF, iso_3166_2) %>%
              summarise(SUM = sum(VALUE)) %>%
              mutate(LOC = "All")) %>%
  mutate(LOC = factor(LOC, levels = c("All",
                                      "Head",
                                      "Distal",
                                      "Total")))
```

```{r}
df_panc_prf_loc <- df_panc_prf_loc %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  ungroup()

df_panc_prf_loc 
```

```{r}
df_panc_prf_loc <- df_panc_prf_loc %>%
  mutate(ADJ = SUM/POP * 10^2)
```

```{r}
df_panc_prf_loc <- df_panc_prf_loc %>%
  filter(LOC != "Total")
```


```{r}
df_panc_prf_loc_long <- df_panc_prf_loc %>%
  pivot_longer(cols = c(SUM, ADJ),
               values_to = "VALUE",
               names_to = "CAT")
```

# plot

```{r}
# turn NA 

df_panc_prf_loc_long_na <- df_panc_prf_loc_long %>%
  mutate(VALUE = case_when(YEAR == "2017" & LOC %in% c("Distal", "Total") ~ NA,
                           .default = VALUE))
```

```{r}
df_panc_prf_q <- df_panc_prf_loc_long_na %>%
  group_by(LOC, CAT, YEAR) %>%
  summarise(q_0 = quantile(VALUE, probs = 0, na.rm = TRUE),
            q_10 = quantile(VALUE, probs = 0.1, na.rm = TRUE),
            q_20 = quantile(VALUE, probs = 0.2, na.rm = TRUE),
            q_30 = quantile(VALUE, probs = 0.3, na.rm = TRUE),
            q_40 = quantile(VALUE, probs = 0.4, na.rm = TRUE),
            q_50 = quantile(VALUE, probs = 0.5, na.rm = TRUE),
            q_60 = quantile(VALUE, probs = 0.6, na.rm = TRUE),
            q_70 = quantile(VALUE, probs = 0.7, na.rm = TRUE),
            q_80 = quantile(VALUE, probs = 0.8, na.rm = TRUE),
            q_90 = quantile(VALUE, probs = 0.9, na.rm = TRUE),
            q_100 = quantile(VALUE, probs = 1.0, na.rm = TRUE))
```

```{r}
df_panc_prf_q_long <- df_panc_prf_q %>%
  pivot_longer(cols = starts_with("q_"),
               names_to = "QT",
               values_to = "VALUE")

df_panc_prf_q_long
```


```{r}
df_panc_prf_q_long <- df_panc_prf_q_long %>%
  mutate(QT = str_remove( QT, "^q_")) %>%
  mutate(QT = as.numeric(QT)) %>%
  filter(! QT %in% c(0, 100) ) %>%
  mutate(COL = case_when(QT %in% c(10, 90) ~ 1,
                         QT %in% c(20, 80) ~ 2,
                         QT %in% c(30, 70) ~ 3,
                         QT %in% c(40, 60) ~ 4,
                         QT %in% 50 ~ 5)) %>%
  mutate(COL = factor(COL, levels = 1:5))
```


```{r}
convert_label <- function(x){
  if (x %in% c("SUM")){
    return("**Count (n)**")
  }
  
  else if (x %in% c("ADJ")){
    return("**n/10<sup>5</sup> people**")
  }
  
  else {
    return(NA)
  }
}

convert_label <- Vectorize(convert_label)
```

```{r}
df_panc_prf_loc_long_na  %>%
  filter(!is.na(VALUE)) %>%
  group_by(LOC, CAT) %>%
  summarise(MAX = max(VALUE))
```


```{r}
df_panc_prf_q %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
  filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1")+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8")+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090")+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43")+
    geom_line(data = df_panc_prf_loc_long_na  %>%
                filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
              mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.5,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  
  
    geom_point(aes(YEAR, q_50),
            colour = "black",
            size = 1)+
  
  
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.4)+
  facet_grid2(rows = vars(CAT),
              cols = vars(LOC),
              axes = "all",
              remove_labels = "x",
              scales = "free",
              switch = "y",
              labeller = labeller(CAT = convert_label ))+
  scale_x_continuous(limits = c(2014, 2024),
                     breaks = seq(2014, 2024, 5),
                     labels = c("2014", "2019", "2024"))+
   labs(tag = "a",
        x = "Year")+
  theme_classic()+
   theme(plot.tag = element_text(size =12, colour = "black", face = "bold"),
         plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust = 0.5),
         strip.background = element_blank(),
         strip.text.x = element_markdown(size = 8, colour = "black", face = "bold"),
         strip.text.y.left = element_markdown(size = 8, colour = "black", face = "bold"),
         strip.placement = "outside",
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_blank(),
        axis.text.x = element_text(size = 8, colour = "black"), 
                               #  angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))
```

```{r}
df_panc_prf_loc %>%
  group_by(LOC) %>%
  summarise(SUM_max = max(SUM),
            ADJ_max = max(ADJ))
```



```{r}
loc_levels <- c("All", "Head", "Distal")

df_scale_sum <- tibble(LOC = loc_levels,
                       YMAX = c(2500, 1500, 1000),
                       YBRK = c(500, 500, 250))

df_scale_adj <- tibble(LOC = loc_levels,
                       YMAX = c(20, 15, 8),
                       YBRK = c(4, 5, 2))


```

```{r}
list_p1_a1 <- purrr::map(loc_levels, function(loc){
  
  ymax <- df_scale_sum %>% filter(LOC == loc) %>% pull(YMAX)
  
  ybrk <- df_scale_sum %>% filter(LOC == loc) %>% pull(YBRK)
  
  df_panc_prf_q  %>% 
    filter(CAT == "SUM") %>%
    filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
    filter(LOC == loc) %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43", alpha = 0.5)+
    geom_line(data = df_panc_prf_loc_long_na  %>%
                filter(CAT == "SUM") %>%
                filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
                filter(LOC == loc) %>% 
                mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.5,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.4)+
  scale_x_continuous(limits = c(2014, 2024),
                     breaks = seq(2014, 2024, 5),
                     labels = c("2014", "2019", "2024"))+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk),
                       labels = scales::label_comma())+
   labs(title = loc,
        x = "Year",
        y = "**n**")+
  theme_classic()+
   theme(
         plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust = 0.5,
                                  margin = margin(0, 0, 1, 0, "mm")),
         strip.background = element_blank(),
         strip.text.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"), 
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 1, 1, 1, unit = "mm"))
} )


```


```{r}
for (i in 1:length(list_p1_a1)){
  print(list_p1_a1[[i]])
}
```

```{r}
for (i in 1:length(list_p1_a1)){
  assign( paste0("p1_a", i), list_p1_a1[[i]])
}
```

```{r}
p1_a1 <- p1_a1 +
  labs(tag = "a")+
  theme(plot.tag = element_text(size =12, colour = "black", face = "bold"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p1_a2 <- p1_a2 +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p1_a3 <- p1_a3 +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```



```{r}
list_p1_b <- purrr::map(loc_levels, function(loc){
  
  ymax <- df_scale_adj %>% filter(LOC == loc) %>% pull(YMAX)
  
  ybrk <- df_scale_adj %>% filter(LOC == loc) %>% pull(YBRK)
  
  df_panc_prf_q %>% 
    filter(CAT == "ADJ") %>%
    filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
    filter(LOC == loc) %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43", alpha = 0.5)+
    geom_line(data = df_panc_prf_loc_long_na  %>%
                filter(CAT == "ADJ") %>%
                filter(!(YEAR == "2017" & LOC %in% c("All","Distal"))) %>%
                filter(LOC == loc) %>% 
                mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.7,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.3)+
  scale_x_continuous(limits = c(2014, 2024),
                     breaks = seq(2014, 2024, 5),
                     labels = c("2014", "2019", "2024"))+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk),
                       labels = scales::label_comma())+
    coord_cartesian(clip = "off")+
   labs(
        x = "Year",
        y = "**n/10<sup>5</sup> people**")+
  theme_classic()+
   theme(
         
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"), 
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 1.5, 0, 1.5, unit = "mm"))
} )


```

```{r}
for (i in 1:length(list_p1_b)){
  print(list_p1_b[[i]])
}
```

```{r}
for (i in 1:length(list_p1_b)){
  assign( paste0("p1_b", i), list_p1_b[[i]])
}
```



```{r}
p1_b2 <- p1_b2 +
  theme(axis.title.y = element_blank())

p1_b3 <- p1_b3 +
  theme(axis.title.y = element_blank())
```



# add time series

```{r}
df_panc_prf_loc_long_na <- df_panc_prf_loc_long_na  %>%
  mutate(BLOCK = str_remove(iso_3166_2, "JP\\-")) %>%
  mutate(BLOCK = as.numeric(BLOCK)) %>%
  mutate(ID = paste0(LOC, "_", CAT))
```


```{r}
# man kendall test on raw values


df_panc_prf_rkt <- df_panc_prf_loc_long_na %>%
  
  mutate(YEAR = as.numeric(YEAR)) %>%
  ungroup() %>%
  nest(data = -ID) %>%
  mutate(
    model = purrr::map(data, ~ rkt(date = .x$YEAR,
                                 y = .x$VALUE,
                                 block = .x$BLOCK,
                                 correct = TRUE)),
    tau = map_dbl(model, "tau"),
    p_value = map_dbl(model, "sl"),
    p_value_cor = map_dbl(model, "sl.corrected"),
    slope = map_dbl(model, "B")
  )

df_panc_prf_rkt

```

```{r}
# split ID

df_panc_prf_res <- df_panc_prf_rkt %>%
  separate_wider_delim(cols = ID,
                       delim = "_",
                       names = c("LOC", "CAT"))

```

```{r}
levels_prf <- df_panc_prf %>% arrange(PRF) %>% distinct(PRF) %>% pull(PRF)
```


```{r}
df_panc_prf_res <- df_panc_prf_res %>%
  mutate(LOC = factor(LOC, levels = c("All", "Head", "Distal"))) %>%
  mutate(CAT = factor(CAT, levels  = c("ADJ" ,"SUM")))
```


```{r}
format_p <- function(x){
  if (x > 0.001){
    p <- formatC(x, digits = 2, format = "fg", flag = "#" )
    return(p)
  }
  
  else {
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    num <- p %>% str_extract(".+(?=e)")
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    p <- str_c(num, "×10^", ex)
    return(p)
  }
}

format_pv <- Vectorize(format_p)
```

```{r}
get_exp <- function(x){

  if (x > 0.001){
    
    return("")
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    
    return(ex)
  }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){

    if (x > 0.001){
    
      p <- formatC(x, digits = 2, format = "fg", flag = "#")
      
      return(p)
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
df_panc_prf_res
```


```{r}
df_panc_prf_res <- df_panc_prf_res %>%
  
   mutate(slope_label = case_when(abs(slope) < 10 ~ formatC(slope, digits = 2, format = "fg", flag= "#"),
                                 .default = round(slope) %>% as.character())) %>%
  mutate(slope_label = str_replace(slope_label, "\\.$", "\\.0$")) %>%
  
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
  
#  mutate(tau_label = as.numeric(tau_label)) %>%
  
  mutate(p_num = get_numv(p_value_cor) ) %>%
  
  mutate(p_exp = get_expv(p_value_cor)) %>%
  
  mutate(p_symbol = case_when(p_value < 0.001 ~ "***",
                              p_value < 0.01 ~ "**",
                              p_value < 0.05 ~ "*",
                              .default = "")) %>%
  
  mutate(label_beta = paste0("beta == '", slope_label, "'"),
         y_beta = 0.3) %>%
  
  mutate(label_tau = paste0("tau == '", tau_label, "'")) %>%
  
  mutate(label_p = paste0("italic(p) == '", p_num, "'^'", p_exp, "'"),
         y_p = -0.3) %>%
  
  mutate(across(starts_with("label_"), ~ str_replace_all(.x, "-", "−")))

df_panc_prf_res
  
```


```{r}
t1 <- df_panc_prf_res %>%
  arrange(LOC) %>%
  mutate(p_exp = if_else(p_exp == "+00", "-14", p_exp)) %>%
  mutate(p_exp = str_replace_all(p_exp, "-", "−")) %>%
  mutate(p_num = if_else(p_num == "0.0×10", "< 1.0×10", p_num)) %>%
  
   mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))
  }) ) 

t1 
```


```{r}
t1_a <- t1 %>% filter(CAT == "SUM") %>%
  select(LOC, slope_label, tau_label, p_label )

t1_b <- t1 %>% filter(CAT == "ADJ") %>%
  select(LOC, slope_label, tau_label, p_label )
```

```{r}
t1_ab <- t1_a %>%
  left_join(t1_b,
            by = join_by(LOC),
            suffix = c("_sum", "_adj"))

t1_ab
```

```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t1_ab) %>%
  wb_save("../table/TableS_prf_rkt.xlsx")
```



```{r}
p1_c <- 
  df_panc_prf_res %>%
  
  mutate(CAT = case_when(CAT == "SUM" ~ "**n**",
                         CAT == "ADJ" ~ "**n/10<sup>5</sup> people**")) %>%
  
  mutate(CAT = factor(CAT,
                      levels = c("**n/10<sup>5</sup> people**",
                                 "**n**"))) %>%
  
  ggplot(aes(LOC, CAT, fill = tau))+
  geom_tile(linewidth = 0.3, colour = "black") +
  scale_fill_gradient2(low = "#74add1",
                      mid  = "white",
                      high = "#f46d43",
                      limits = c(-1, 1),
                      name = expression(tau))+
  
  geom_text(aes(label = label_beta, nudge_y = y_beta),
            size= 2.8, colour = "black",
                parse = TRUE)+
  
  geom_text(aes(label = label_tau),
            size= 2.8, colour = "black",
                parse = TRUE)+
  
  geom_text(aes(label = label_p, nudge_y = y_p),
            size= 2.8, colour = "black",
                parse = TRUE)+
  coord_cartesian(clip = "off")+
  theme_classic()+
    guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  labs(tag = "b",
       x = "Location")+
    theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
          axis.title.x =  element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_markdown(size = 8, colour = "black", face = "bold"),
          axis.text.y = element_markdown(size = 8, colour = "black", face = "bold"),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
          legend.key.height = unit(1, "lines"),
          legend.key.width = unit(0.75, "lines"),
          plot.margin = margin(0, 0, 0, 0, "mm"),
          legend.margin = margin(0, 0, 0, 0, "mm"))

p1_c

```

# dummy legend

```{r}
# create dummy variable
# ribbon

df_panc_prf_leg <- df_panc_prf_q_long %>%
   mutate(QTR = case_when(QT %in% c(10, 90) ~ "10–90th",
                         QT %in% c(20, 80) ~ "20–80th",
                         QT %in% c(30, 70) ~ "30–70th",
                         QT %in% c(40, 60) ~ "40–60th",
                         QT %in% 50 ~ "Median"))
```



```{r}

p1_dum <-  ggplot()+
  
  geom_line(data = df_panc_prf_leg %>%
             filter(LOC == loc_levels[2]) %>%
             filter(QTR == "Median"),
           aes(YEAR, VALUE, group = QTR, colour = QTR),
          linewidth = 0.5)+
  
  scale_colour_manual(values = "black",
                      name = "Trend")+
  
  geom_col(data = df_panc_prf_leg %>%
             filter(LOC == loc_levels[2]) %>%
             filter(QTR != "Median"),
           aes(YEAR, VALUE, fill = QTR),
           colour = "black",
           linewidth = 0.3)+

  scale_fill_manual(values = c("#74add1", "#e0f3f8", "#fee090", "#f46d43"),
                    name = "Percentile")+

  guides(fill = guide_legend(order = 2,
                             ncol = 1,
                             override.aes = list(colour = "black",
                                                 linewidth = 0.1,
                                                 alpha = 0.5)),
         colour = guide_legend(order = 1,
                               override.aes = list(colour = "black",
                                                 linewidth = 0.5)
                               )) +

  theme_classic()+
  theme(legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "bottom",
        legend.title.position = "top",
        legend.box = "vertical",
        legend.box.just = "left",
        legend.justification = "left",
        legend.text.align = 1,
        legend.key.size = unit(5, "mm"),
        legend.spacing.y = unit(5, "mm"),
        legend.key.spacing.y = unit(0, "mm"),
       # legend.spacing.y = unit(2.5, "mm"),
      #  legend.justification = c(0, 0.5),
        theme(legend.background = element_rect(fill = "transparent", color = NA)),
        legend.margin = margin(0, 1, 0, 2, unit = "mm"),
      legend.box.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_dum 
```



```{r}
p1_leg <- p1_dum %>% get_legend() %>% wrap_plots()

p1_leg 
```

```{r}
list_plot <- list(p1_a1, p1_a2, p1_a3,
               p1_b1, p1_b2, p1_b3, 
               p1_leg)
```

```{r}
name_plot <- c("p1_a1", "p1_a2", "p1_a3",
               "p1_b1", "p1_b2", "p1_b3", 
               "p1_leg")

path_plot <- paste0("../plot/prf/", name_plot, ".RDS")
```

```{r}
for (i in 1:length(list_plot)){
  saveRDS(object = list_plot[[i]],
          file = path_plot[i])
}

```

```{r}
name_plot <- list.files("../plot/prf") %>% str_remove("\\.RDS")
```

```{r}
path_plot <- paste0("../plot/prf/", name_plot, ".RDS")
```



```{r}
p1_a_ex <- readRDS(path_plot[1])
```


```{r}
for (i in 1:length(name_plot)){
  assign(name_plot[i], readRDS(path_plot[i]))
}
```


```{r}
p1 <- p1_a1 + p1_a2 + p1_a3 +
  p1_b1 + p1_b2 + p1_b3 +
  p1_leg +
  
 # patchwork::free(p1_leg, side = "lr")+
  patchwork::free(p1_c)+
  plot_layout(design = "
              AAABBBCCC
              AAABBBCCC
              AAABBBCCC
              AAABBBCCC
              DDDEEEFFF
              DDDEEEFFF
              DDDEEEFFF
              DDDEEEFFF
              ##GGGGG##
              HHHHHHHHH
              HHHHHHHHH
              HHHHHHHHH")

p1

# ggsave("../figure/Fig5.pdf", p1,
#       width = 175, height = 175, units = "mm",
#       device = cairo_pdf)
```


```{r}
saveRDS(df_panc_prf_rkt, "../df/rkt/df_panc_prf_rkt.RDS")
```

