---
title: "Pancreatic cacner"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(fpp3)
library(ggtext)
library(ggrepel)
library(ggh4x)

library(patchwork)
library(scales)

library(sf)
library(mapdata)
```


```{r}
# make df folder

dir.create("../plot", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../plot/prf_2023", showWarnings = TRUE, recursive = FALSE, mode = "0777")

```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop_prf <- readRDS("../rds/pop/prf/df_pop_prf")
```



```{r}
map_jp <-  maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF))
```

# clean

```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(VALUE = replace_na(VALUE, 0))
```


```{r}
df_pop_prf <- df_pop_prf %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", PRF))
```


```{r}
# add region

df_pop_prf <- df_pop_prf %>%
  left_join(df_surg_prf %>% 
              distinct(iso_3166_2, REG),
            by = join_by(iso_3166_2))
```


# pancreas

```{r}
df_surg_prf %>% 
  filter(str_detect(CLASS_code, "^K702|^K703|^K704")) %>%
  count(CLASS_code, CLASS_name, PRO_code, PRO_name)
```


```{r}
df_panc_prf <-  df_surg_prf %>% 
       filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code %in% c("K700", "K700-4") ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Partial")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Partial")))
```

```{r}
# check total

df_surg_prf %>%
  filter(str_detect(CLASS_code, "^K704"))  %>%
  group_by(YEAR) %>%
  summarise(VALUE = sum(VALUE)) %>%
  left_join(df_surg_prf %>%
              filter(str_detect(CLASS_code, "^K704"))  %>%
              distinct(PRO_name, YEAR, .keep_all = TRUE) %>%
              select(YEAR, TOTAL),
            by = join_by(YEAR)) %>%
  mutate(DIF = (VALUE- TOTAL)/TOTAL * 100 )
```



```{r}
df_panc_prf %>%
  filter(YEAR == "2023") %>%
  group_by(YEAR, PRO_name) %>%
  summarise(SUM = sum(VALUE)) %>%
  ungroup() %>%
  left_join(df_panc_prf %>%
              filter(YEAR == "2023") %>%
              distinct(YEAR, PRO_name, .keep_all = TRUE) %>%
              select(PRO_name, TOTAL),
            by = join_by(PRO_name)) %>%
  summarise(SUM = sum(SUM),
            TOTAL = sum(TOTAL)) 
```

```{r}
df_panc_total <- df_panc_prf %>%
  distinct(YEAR, PRO_name, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM_total = sum(TOTAL))

df_panc_total
```

```{r}
df_panc_value <- df_panc_prf %>%
  group_by(YEAR) %>%
  summarise(SUM_value = sum(VALUE))

df_panc_value
```

```{r}
df_panc_total %>%
  left_join(df_panc_value,
            by = join_by(YEAR)) %>%
  mutate(PCT = (SUM_value - SUM_total)/SUM_total * 100)
```



```{r}
df_panc_prf %>%
  group_by(YEAR, PRO_name) %>%
  mutate(RN = n()) %>%
  count(RN)
```


```{r}
df_panc_prf %>%
  group_by(YEAR, PRO_name) %>%
  mutate(RN = n()) %>%
  filter(VALUE != 0) %>%
  count(RN)
```

```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(SUM = sum(VALUE)) %>%
  filter(SUM == 0)
```



```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(SUM = sum(VALUE)) %>%
  ggplot(aes(PRF, SUM, fill = REG)) +
  geom_col(width= 0.7) +
  facet_grid(rows = vars(YEAR))+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR, SUM, group = PRF, colour = REG)) +
  geom_line(linewidth= 0.3) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(limits = c(0, NA))+
  facet_wrap2(vars(PRF),
              scales = "free_y")+
  theme_classic()+
  theme(strip.background = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, REG, LOC) %>%
  mutate(SUM = sum(VALUE)) %>%
#  filter(YEAR != "2017") %>%
#  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, SUM, group = LOC, colour = LOC)) +
  geom_line(linewidth= 0.3) +
  scale_colour_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(limits = c(0, NA))+
  facet_wrap2(vars(PRF),
              scales = "free_y")+
  theme_classic()+
  theme(strip.background = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5))
```



```{r}
p1_a1 <- df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024") %>%
  ggplot(aes(PRF, SUM, fill = REG)) +
  geom_col(width = 0.7) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 2500),
                     breaks = seq(0, 2500, 500),
                     labels = scales::label_comma())+
  theme_classic()+
  labs(tag = "a",
       x = "Prefecture",
       y = "n")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 3, 0, unit = "mm"))

p1_a1 
```


```{r}
p1_c1 <- map_jp %>%
  left_join(df_panc_prf %>%
              group_by(YEAR, PRF, REG) %>%
              summarise(SUM = sum(VALUE)) %>%
              filter(YEAR == "2024"),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = SUM), linewidth = 0.2)+
   scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0, 2500),
                     labels = label_comma(),
                     name = "**n**") +
#  labs(fill = "**n**")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
    scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
 labs(tag = "c")+
  theme_void()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_markdown(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 1),
        legend.justification.inside = c(0, 1),
        legend.background = element_blank(),
        legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_c1
```

```{r}
# region

df_panc_prf %>%
  group_by(YEAR, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024") %>%
    ggplot(aes(REG, SUM, fill = REG)) +
  geom_col(width = 0.7) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 6000),
                     breaks = seq(0, 6000, 1000),
                     labels = scales::label_comma())+
  theme_classic()+
  labs(tag = "a",
       x = "Region",
       y = "Count (n)")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 3, 0, unit = "mm"))
```



```{r}
# calculalte proprtion based on prf and align in descending order

df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024") %>%
  left_join(df_panc_total,
            by = join_by(YEAR)) %>%
  ungroup() %>%
  mutate(PCT = SUM/SUM_total * 100) %>%
  slice_max(PCT, n = 13) %>%
  ggplot(aes(PCT, fct_reorder( PRF, PCT ), fill = REG))+
  geom_col(width = 0.7)+
    scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0, 15),
                     breaks = seq(0, 15, 5))+
  theme_classic()
```

```{r}
levels_pct_prf <- df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024") %>%
  left_join(df_panc_total,
            by = join_by(YEAR)) %>%
  ungroup() %>%
  mutate(PCT = SUM/SUM_total * 100) %>%
  arrange(desc(PCT)) %>%
  pull(PRF) %>%
  as.character()


levels_pct_prf 
```

```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024") %>%
  left_join(df_panc_total,
            by = join_by(YEAR)) %>%
  ungroup() %>%
  mutate(PCT = SUM/SUM_total * 100) %>%
    mutate(PRF = case_when(PRF %in% levels_pct_prf[1:15] ~ PRF,
                         .default = "Others"))
```

# panc

```{r}
df_panc_prf %>%
  filter(YEAR == "2024") %>%
  group_by(YEAR, PRF, TX, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  ggplot(aes(PRF, PCT, fill = TX))+
  geom_col(width = 0.7)+
  scale_fill_manual(values = c("#1f77b4",
                                   "#d62728",
                                   "#bcbd22"))+
  scale_y_continuous(expand = c(0, 0))+
  theme_classic()+
    labs(x = "Prefecture",
       y = "Percentage (%)")+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))
```

```{r}
df_panc_prf %>%
  filter(YEAR == "2024" & LOC == "Distal") %>%
  group_by(YEAR, PRF, TX, REG) %>%
  summarise(SUM = sum(VALUE))
```


```{r}
# only distal cancer too many missing values

df_panc_prf %>%
  filter(YEAR == "2024" & LOC == "Distal") %>%
  group_by(YEAR, PRF, TX, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  ggplot(aes(PRF, PCT, fill = TX))+
  geom_col(width = 0.7)+
  scale_fill_manual(values = c("#1f77b4",
                                   "#d62728",
                                   "#bcbd22"))+
  scale_y_continuous(expand = c(0, 0))+
  theme_classic()+
    labs(x = "Prefecture",
       y = "Percentage (%)")+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
      #  legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))
```


```{r}
df_panc_prf %>%
  distinct(YEAR, PRO_name, SHEET) 
```


```{r}
# calculate national average based on "Total" for 2024

df_panc_prf_mean <- df_panc_prf %>%
  distinct(YEAR, PRO_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  left_join(df_pop_prf %>%
              filter(PRF_jp == "total") %>%
              rename(POP =  "ALL_total") %>%
              select(YEAR, POP),
            by = join_by(YEAR)) %>%
  mutate(PCT = SUM/(POP * 10^3) * 10^5) 

df_panc_prf_mean
```

```{r}
df_panc_prf_mean %>% filter(YEAR == "2024") %>% pull(PCT)
```


```{r}
# count prefectures above national average

df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP * 10^3) * 10^5) %>%
  filter(YEAR == "2024") %>%
  filter(PCT > df_panc_prf_mean %>% filter(YEAR == "2024") %>% pull(PCT))


```

```{r}
p1_a2 <- df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP * 10^3) * 10^5) %>%
  filter(YEAR == "2024") %>%
    ggplot(aes(PRF, PCT, fill = REG)) +
  geom_col(width = 0.7) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  geom_hline(yintercept = df_panc_prf_mean %>%
               filter(YEAR == "2024") %>% pull(PCT),
             colour = "black", linewidth = 0.3, linetype = 2
             )+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 20),
                     breaks = seq(0, 20, 5),
                     labels = scales::label_comma())+
  theme_classic()+
  labs(x = "Prefecture",
       y = "n/10<sup>5</sup> people")+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 3, 0, unit = "mm"))

p1_a2 
```


```{r}
p1_c2 <- map_jp %>%
  left_join(df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP * 10^3) * 10^5) %>%
  filter(YEAR == "2024"),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = PCT), linewidth = 0.2)+
   scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0, 20),
                     labels = label_comma()) +
  labs(#tag = "c",
       fill = "**n/10<sup>5</sup> people**")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  theme_void()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_markdown(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 1),
        legend.justification.inside = c(0, 1),
        legend.background = element_blank(),
        legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_c2
```

```{r}
df_pop_prf %>%
  filter(!is.na(REG)) %>%
  group_by(YEAR, REG) %>%
  summarise(POP = sum(ALL_total)) %>%
  mutate(ID = paste0(REG, "_", YEAR)) %>%
  ungroup() %>%
  select(ID, POP)
```
 
 
```{r}
# region

df_panc_prf %>%
  group_by(YEAR, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(REG, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              filter(!is.na(REG)) %>%
              group_by(YEAR, REG) %>%
              summarise(POP = sum(ALL_total)) %>%
              mutate(ID = paste0(REG, "_", YEAR)) %>%
              ungroup() %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP * 10^3) * 10^5) %>%
  filter(YEAR == "2024") %>%
    ggplot(aes(REG, PCT, fill = REG)) +
  geom_col(width = 0.7) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  geom_hline(yintercept = df_panc_prf_mean %>%
               filter(YEAR == "2024") %>% pull(PCT),
             colour = "black", linewidth = 0.3, linetype = 2
             )+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 20),
                     breaks = seq(0, 20, 5),
                     labels = scales::label_comma())+
  theme_classic()+
  labs(x = "Prefecture",
       y = "n per 10<sup>5</sup> people")+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 3, 0, unit = "mm"))
```
 
 
```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID))
```

 
 
```{r}
df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  ungroup() %>%
  nest(data = -YEAR) %>%
  mutate(
    fit = purrr::map(data, ~ lm(SUM ~ POP, data = .x)),
    tidied = purrr::map(fit, broom::tidy)
  ) %>%
  unnest(tidied) %>%
  filter(term == "POP")
```
 

```{r}
df_panc_prf_lm <- df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  ungroup() %>%
  mutate(POP = POP/10^3) %>%
  nest(data = -YEAR) %>%
  mutate(
    fit = purrr::map(data, ~ lm(SUM ~ POP, data = .x)),
    tidied = purrr::map(fit, broom::tidy),
    glanced = purrr::map(fit, glance),
  ) 
```

```{r}
df_panc_prf_lm %>% unnest(tidied) %>% filter(term == "POP")
```


```{r}
df_panc_prf_lm %>% unnest(glanced)
```

```{r}
# calculate equation

df_panc_prf_label <- df_panc_prf_lm %>% unnest(tidied) %>%
  select(YEAR, term, estimate) %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  mutate(slope = round(POP, digits = 0)) %>%
  mutate(intercept = round(Intercept, digits = 0)) %>%
  mutate(label = paste0("*y* = ", slope, "*x*", intercept )) %>%
  mutate(label = str_replace(label, "\\-", " \\- "))

df_panc_prf_label
```


```{r}
df_panc_prf_p <- df_panc_prf_lm %>%
  unnest(glanced) %>%
  mutate(adj_r2 = round(adj.r.squared, digits = 2)) %>%
  mutate(adj_r2 = format(adj_r2, nsmall = 2)) %>%
  mutate(adj_r2 = str_remove_all(adj_r2, "\\s")) %>%
  mutate(p_val = case_when(p.value < 0.001 ~ "*p* < 0.001",
                           .default = NA)) %>%
  select(YEAR, p_val, adj_r2)


df_panc_prf_p
```


```{r}
df_panc_prf_label <- df_panc_prf_label %>%
  left_join(df_panc_prf_p,
            by = join_by(YEAR)) %>%
  mutate(label = paste0(label, "<br>", p_val, "<br>",
                        "*R*<sup>2</sup><sub>adj</sub> = ", adj_r2))

df_panc_prf_label 
```


```{r}
df_panc_prf_plot <- df_panc_prf %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(iso_3166_2, "_", YEAR) )%>%
  left_join(df_pop_prf %>%
              mutate(ID = paste0(iso_3166_2, "_", YEAR)) %>%
              rename(POP =  "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  filter(YEAR == "2024") %>%
  mutate(POP = POP/10^3)
```


```{r}
#p1_b <- 
df_panc_prf_plot %>%
  ggplot(aes(POP, SUM))+
  geom_point(aes(fill = REG),
             size = 1.5, alpha = 0.8, shape = 21,
             stroke = 0.3)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_x_continuous(limits = c(0, 15),
                     breaks = seq(0, 15, 5))+
  scale_y_continuous(limits = c(0, 2500),
                     breaks = seq(0, 2500, 500),
                     labels = label_comma())+
  geom_richtext(data = df_panc_prf_label %>% filter(YEAR == "2024"),
            aes(label = label),
            x = 0, y = 2500,
            hjust = 0, vjust = 1,
            size = 2.8, colour = "black",
            fill = NA, label.color = NA,
            label.padding = grid::unit(rep(0, 4), "pt"))+

  geom_smooth(method = "lm",
              se = FALSE,
              colour = "#17becf",
              linewidth = 0.3,
              alpha = 0.3)+
  geom_text_repel(data = df_panc_prf_plot %>% 
                    filter(PRF %in% c("Tokyo",
                                      "Osaka",
                                      "Kanagawa",
                                      "Aichi",
                                      "Saitama",
                                      "Chiba")),
                  aes(label= PRF),
                  size = 2.6, colour = "black",
                  segment.size = 0.3)+
  theme_classic()+
   labs(tag = "b",
        x = "Prefecture population (10<sup>6</sup>)",
        y = "Pancreatic surgery (n)")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

#p1_b
```
 

```{r}
# linear association between head and disatl

df_panc_prf %>%
  group_by(YEAR, PRF, LOC) %>%
  summarise(SUM = sum(VALUE)) %>%
  filter(YEAR == "2024")
```


```{r}
df_panc_prf_loc <- df_panc_prf %>%
  group_by(YEAR, iso_3166_2, PRF, REG, LOC) %>%
  summarise(SUM = sum(VALUE)) %>%
  ungroup() %>%
 # select(!YEAR) %>%
  pivot_wider(values_from = SUM,
              names_from = LOC)
```

```{r}
df_panc_prf_loc 
```


```{r}
lm(Distal ~ Head,
   data = df_panc_prf_loc) %>%
  summary()
```


```{r}
df_panc_prf_loc_lm <- df_panc_prf_loc %>%
  nest(data = -YEAR) %>%
  mutate(
    fit = purrr::map(data, ~ lm(Head ~ Distal, data = .x)),
    tidied = purrr::map(fit, broom::tidy),
    glanced = purrr::map(fit, glance),
  ) 
```



```{r}
# calculate equation

df_panc_prf_loc_label <- df_panc_prf_loc_lm %>% unnest(tidied) %>%
  select(YEAR, term, estimate) %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  mutate(slope = formatC(Distal, digits = 3, format = "fg", flag = "#")) %>%
  mutate(intercept = formatC(Intercept, digits = 3, format = "fg", flag = "#")) %>%
  mutate(label = paste0("*y* = ", slope, "*x* + ", intercept ))

df_panc_prf_loc_label
```


```{r}
df_panc_prf_loc_p <- df_panc_prf_loc_lm %>%
  unnest(glanced) %>%
  mutate(adj_r2 = round(adj.r.squared, digits = 2)) %>%
  mutate(adj_r2 = format(adj_r2, nsmall = 2)) %>%
  mutate(adj_r2 = str_remove_all(adj_r2, "\\s")) %>%
  mutate(p_val = case_when(p.value < 0.001 ~ "*p* < 0.001",
                           .default = NA)) %>%
  select(YEAR, p_val, adj_r2)


df_panc_prf_loc_p
```


```{r}
df_panc_prf_loc_label <- df_panc_prf_loc_label %>%
  left_join(df_panc_prf_loc_p,
            by = join_by(YEAR)) %>%
  mutate(label = paste0(label, "<br>", p_val, "<br>",
                        "*R*<sup>2</sup><sub>adj</sub> = ", adj_r2))

df_panc_prf_loc_label
```

```{r}
df_panc_prf_loc %>% 
  filter(YEAR == "2024") %>%
  arrange(desc(Head))
```

```{r}
df_panc_prf_loc %>% 
  filter(YEAR == "2024") %>%
  arrange(desc(Distal))
```


```{r}
df_panc_prf_loc %>% 
  filter(YEAR == "2024") %>%
  arrange(desc(Head))
```


```{r}
df_panc_prf_loc_name <- df_panc_prf_loc %>% 
  filter(YEAR == "2024") %>%
  filter(PRF %in% c("Tokyo",
                    "Osaka",
                    "Kanagawa",
                    "Aichi",
                    "Saitama",
                    "Chiba",
                    "Hokkaido",
                    "Fukuoka",
                    "Hyogo",
                    "Shizuoka",
                    "Miyagi",
                    "Hiroshima",
                    "Kyoto"
                    #, "Okayama"
                    ))
```

```{r}
df_panc_prf_loc_name <- df_panc_prf_loc_name %>%
  
   mutate(hjust = case_when(PRF == "Tokyo" ~ 0,
                           PRF == "Osaka" ~ 0,
                           PRF == "Kanagawa" ~ 0.5,
                           PRF == "Aichi" ~ 0,
                           PRF == "Chiba" ~ 1,
                           PRF == "Saitama" ~ 1,
                           PRF == "Hokkaido" ~ 0,
                           PRF == "Hyogo" ~ 0,
                           PRF == "Fukuoka" ~ 1,
                           PRF == "Shizuoka" ~ 0,
                           PRF == "Miyagi" ~ 1,
                           PRF == "Kyoto" ~ 0,
                           PRF == "Hiroshima" ~ 0,
                           PRF == "Okayama" ~ 0)) %>%
  
  mutate(vjust = case_when(PRF == "Tokyo" ~ 0,
                           PRF == "Osaka" ~ 0,
                           PRF == "Kanagawa" ~ 0,
                           PRF == "Aichi" ~ 0.5,
                           PRF == "Hokkaido" ~ 0,
                           PRF == "Chiba" ~ 0,
                           PRF == "Saitama" ~ 0,
                           PRF == "Hyogo" ~ 0.5,
                           PRF == "Fukuoka" ~ 0.5,
                           PRF == "Shizuoka" ~ 0,
                           PRF == "Miyagi" ~ 0,
                           PRF == "Shizuoka" ~ 0,
                           PRF == "Kyoto" ~ 1,
                           PRF == "Hiroshima" ~ 0.5,
                           PRF == "Okayama" ~ 1)) %>%
  
  mutate(x = case_when(PRF == "Miyagi" ~ Distal,
                       PRF == "Hiroshima" ~ Distal + 1000/15,
                       hjust == 0 ~ Distal + 1000/30,
                       hjust == 0.5 ~ Distal,
                       hjust == 1 ~ Distal - 1000/30)) %>%
  
  mutate(y = case_when(
                       vjust == 0 ~ Head + 1500/30,
                       vjust == 1 ~ Head - 1500/30,
                       vjust == 0.5 ~ Head))

df_panc_prf_loc_name 
```


```{r}
p1_b <- df_panc_prf_loc %>%
  filter(YEAR == "2024") %>%
  ggplot(aes( Distal, Head))+
  geom_point(aes(fill = REG),
             size = 1.5, shape = 21,
            colour = "black", alpha = 0.7,
            stroke = 0.3)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  geom_richtext(data = df_panc_prf_loc_label %>% filter(YEAR == "2023"),
            aes(label = label),
            x = 0, y = 1600,
            hjust = 0, vjust = 1,
            size = 2.8, colour = "black",
            fill = NA, label.color = NA,
            label.padding = grid::unit(rep(0, 4), "pt"))+
  geom_smooth(method = "lm",
              se  = FALSE,
              linewidth = 0.3,
              colour = "#17becf",
              alpha = 0.8)+
  geom_text(data = df_panc_prf_loc_name,
                    aes(x = x, y= y, label = PRF,
                        hjust = hjust, vjust = vjust),
                   size = 2.6, colour = "black")+
  scale_x_continuous(limits = c(0, 1000),
                     breaks = seq(0, 1000, 250),
                     labels = scales::label_comma())+
  scale_y_continuous(limits = c(0, 1600),
                     breaks = seq(0, 1600, 400),
                     labels = scales::label_comma())+
  theme_classic()+
  labs(tag = "b",
       x = "Distal pancreatectomy (n)",
       y = "Pancreatic head resection (n)")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
        legend.background = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_b 
```

```{r}
list_p <- list(p1_a1, p1_a2, p1_b, p1_c1, p1_c2 )
```

```{r}
name_p <- paste0("p1_",
                 c("a1", "a2", "b", "c1", "c2"))
```

```{r}
path_p <- paste0("../plot/prf_2023/", name_p, ".RDS")
```

```{r}
for (i in 1:length(path_p)){
  saveRDS(list_p[[i]], path_p[i])
}
```


```{r}
saveRDS(p1_a1, "../plot/prf_2023/p1_a1.RDS")
saveRDS(p1_a2, "../plot/p1_a2.RDS")

saveRDS(p1_b, "../plot/p1_b.RDS")

saveRDS(p1_c1, "../plot/p1_c1.RDS")
saveRDS(p1_c2, "../plot/p1_c2.RDS")
```

