---
title: "Pancreatic cacner"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(fpp3)
library(ggtext)
library(ggrepel)
library(ggh4x)

library(patchwork)
library(cowplot)
library(scales)

library(sf)
library(mapdata)

library(broom)
library(glue)
```


```{r}
# make df folder

dir.create("../figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop_prf <- readRDS("../rds/pop/prf/df_pop_prf")
```

```{r}
list.files("../rds/cancer/incidence")
```

```{r}
plot_name <- list.files("../plot/prf_2023", pattern = "RDS") %>% str_remove("\\.RDS")

plot_path <- paste0("../plot/prf_2023/", plot_name, ".RDS")
```

```{r}
for (i in 1:length(plot_name)){
  assign(plot_name[i], readRDS(plot_path[i]))
  }
```

```{r}
df_inc_prf_long <- readRDS("../rds/cancer/df_inc_panc_long.RDS")
```

```{r}
df_inc_prf_panc <- df_inc_prf_long %>%
  filter(!is.na(iso_3166_2)) %>%
  filter(SEX == "Total") %>%
  distinct(YEAR, iso_3166_2, .keep_all = TRUE)
```


```{r}
df_inc_prf_panc <- df_inc_prf_panc %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  rename(INC = "TOTAL")
```


```{r}
map_jp <-  maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF))
```


# clean

```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(VALUE = replace_na(VALUE, 0)) %>%
  mutate(YEAR = as.numeric(YEAR))
```


```{r}
df_pop_prf <- df_pop_prf %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  mutate(YEAR = as.numeric(YEAR))
```


```{r}
# add region

df_pop_prf <- df_pop_prf %>%
  left_join(df_surg_prf %>% 
              distinct(iso_3166_2, REG),
            by = join_by(iso_3166_2))
```


# pancreas

```{r}
df_surg_prf %>% 
  filter(str_detect(CLASS_code, "^K702|^K703|^K704")) %>%
  count(CLASS_code, CLASS_name, PRO_code, PRO_name)
```


```{r}
df_panc_prf <-  df_surg_prf %>% 
     filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code == "K700" ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Partial")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Partial")))
```


```{r}
df_panc_prf_all <- df_panc_prf  %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  ungroup()

df_panc_prf_all 
```

```{r}
#df_inc_prf_panc <- df_inc_prf %>%
#  filter(AGE == "All" & SEX == "All" & str_detect(LOC, "膵"))
```


```{r}
df_panc_prf_all %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2))
```


```{r}
df_panc_prf_all <- df_panc_prf_all %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_inc_prf_panc　%>% select(YEAR, iso_3166_2, INC) %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              select(ID, INC),
            by = join_by(ID)) %>%
  left_join(df_pop_prf %>%　filter(!is.na(iso_3166_2)) %>%
              select(ID, ALL_total) %>%
              rename(POP = "ALL_total"),
            by = join_by(ID))
```

```{r}
df_panc_prf_all <- df_panc_prf_all %>%
  filter(!is.na(INC))
```

```{r}
df_panc_prf_all %>%
  ggplot(aes(INC,SUM))+
  geom_point(aes(fill = REG), 
             size = 1.5, shape = 21,
             colour = "black", alpha = 0.7,
             stroke = 0.3)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
  geom_smooth(method = "lm",
              se  = FALSE,
              linewidth = 0.5,
              colour = "#17becf",
              alpha = 0.8)+
  facet_wrap2(vars(YEAR), ncol = 4)+
  scale_y_continuous(limits = c(0, 5000),
                     breaks = seq(0, 5000, 1000),
                     labels = scales::label_comma()) +
  scale_y_continuous(limits = c(0, 2500),
                     breaks = seq(0, 2500, 500),
                     labels = scales::label_comma())+
  theme_classic()
```

```{r}
# change SUM/1000 for plotting

df_panc_prf_plot <- df_panc_prf_all %>%
  mutate(SUM = SUM/10^3,
         INC = INC/10^3)
```


```{r}
df_panc_prf_lm <-   df_panc_prf_all  %>%
  filter(!is.na(INC)) %>%
  select(PRF, YEAR, SUM, INC) %>%
  nest(data = -YEAR) %>%
  mutate(
    fit = purrr::map(data, ~ lm(SUM ~ INC, data = .x)),
    tidied = purrr::map(fit, tidy),
    glanced = purrr::map(fit, glance),
    augmented = purrr::map(fit, augment)
  )
```

```{r}
df_panc_prf_tidy <- df_panc_prf_lm  %>% unnest(tidied)

df_panc_prf_tidy
```

```{r}
df_panc_prf_wide <- df_panc_prf_tidy %>%
  select(YEAR, term, estimate) %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  pivot_wider( names_from = term,  values_from = estimate)

  
df_panc_prf_wide 
```

```{r}
df_panc_prf_glanced <- df_panc_prf_tidy %>%
  filter(term == "INC") %>%
  select(YEAR, glanced) %>%
  unnest(glanced) %>%
  mutate(r2adj = formatC(adj.r.squared, format = "fg", digits = 2, flag = "#")) %>%
  mutate(pval = if_else(p.value < 0.001, "*p* < 0.001", NA))

df_panc_prf_glanced
```


```{r}
df_panc_prf_label <- df_panc_prf_wide %>%
  mutate(INC = formatC(INC, format = "fg", digits = 2, flag = "#")) %>%
  mutate(Intercept = round(Intercept)) %>%
  mutate(Intercept = str_replace(Intercept, "-", " - ")) %>%
  mutate(label = paste0("*y* = ", INC, "*x*", Intercept))
                         
df_panc_prf_label
```

```{r}
df_panc_prf_label <- df_panc_prf_label %>%
  left_join(df_panc_prf_glanced %>% select(YEAR, r2adj, pval)) %>%
  mutate(label = paste0(label, "<br>",
                        pval, "<br>",
                        "*R*<sup>2</sup><sub>adj</sub> = ", r2adj))

df_panc_prf_label
```

```{r}
df_panc_prf_name <- df_panc_prf_plot %>%
  filter(PRF %in% c("Tokyo",
                    "Osaka",
                    "Kanagawa",
                    "Aichi",
                  #  "Chiba",
                    "Hokkaido",
                  "Fukuoka")) %>%
  mutate(hjust = case_when(PRF == "Tokyo" ~ 0.5,
                           PRF == "Osaka" ~0,
                           PRF == "Kanagawa" ~ 0,
                           PRF %in% c("Aichi", "Fukuoka") ~ 1,
                           PRF == "Hokkaido" ~ 0)) %>%
  
  mutate(vjust = case_when(PRF == "Tokyo" & YEAR == 2023 ~ 1,
                           PRF == "Tokyo" ~ 0,
                           PRF == "Osaka" ~ 0.5,
                           PRF == "Kanagawa" ~ 0.5,
                           PRF %in% c("Aichi", "Fukuoka") ~ 0,
                           PRF == "Hokkaido" ~ 1)) %>%

  
  mutate(x = case_when(hjust == 0 ~ INC + 5/20,
                       hjust == 0.5 ~ INC,
                       hjust == 1 ~ INC - 5/20)) %>%
  
  mutate(y = case_when(PRF == "Tokyo" & YEAR == 2023 ~ SUM -2.5/20,
                     #  PRF %in% c("Tokyo", "Osaka") ~ SUM + 2.5/25,
                       vjust == 0 ~ SUM + 2.5/20,
                       vjust == 1 ~ SUM - 2.5/20,
                       vjust == 0.5 ~ SUM)) 
 
df_panc_prf_name
```


```{r}
df_panc_prf_plot %>%
  summarise(MAX_sum = max(SUM),
            MIN_sum = min(SUM),
            MAX_inc = max(INC),
            MIN_inc = min(INC) )
```
```{r}
df_panc_prf_plot %>%
  filter(is.na(INC))
```
```{r}
df_panc_prf_plot %>%
  filter(is.na(SUM))
```


```{r}
p1_d <- df_panc_prf_plot %>%
  filter(!is.na(INC)) %>%
  ggplot(aes(INC,SUM))+
   geom_point( aes(fill = REG), colour = "black", alpha = 0.7, shape = 21,
               size = 1.5)+
   scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
    facet_wrap2(vars(YEAR),
                axes = "all",
                remove_labels = "all",
                ncol = 4)+
  geom_richtext(data = df_panc_prf_label,
                aes(x = 0, y = 2.5, label = label),
                size = 2.8,
                hjust = 0, vjust = 1,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt")
                )+
    geom_line(stat="smooth",
              method = "lm", 
              linewidth = 0.5,
              linetype = 1,
              alpha = 0.7,
              colour = "#17becf")+
    geom_text(data = df_panc_prf_name,
                    aes(x = x, 
                        y = y,
                        hjust = hjust,
                        vjust = vjust,
                        label = PRF),
                  size = 2.6, 
                  inherit.aes = FALSE)+
    scale_x_continuous(limits = c(0, 5),
                     breaks = seq(0, 5, 1),
                     labels = scales::label_comma()) +
  scale_y_continuous(limits = c(0, 2.5),
                     breaks = seq(0, 2.5, 0.5),
                     labels = scales::label_comma())+
  labs(tag = "d",
       x = "Pancreatic cancer incidence (×10<sup>3</sup>)",
       y = "Pancreatectomy (×10<sup>3</sup>)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(1, 0, 1, 0, "mm")),
        axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        panel.spacing.x = unit(2, "mm"),
        panel.spacing.y = unit(1, "mm"),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_d
```


```{r}
p1_a1 <- p1_a1 + theme(axis.title.x = element_blank(),
                       axis.text.x = element_blank())
```

```{r}
#p1_bd <- wrap_plots(p1_b1, p1_b2, p1_d)

#p1_bd
```

```{r}
p1_b <- p1_b +
  theme(plot.margin = margin(0, 2, 0 , 0, unit = "mm"))

p1_c1 <- p1_c1 + 
  theme(plot.margin = margin(0, 1, 0 , 0, unit = "mm"))

p1_c2 <- p1_c2 + theme(plot.margin = margin(0, 0, 0 , 1, unit = "mm"))
```

# region map

```{r}
map_jp <- maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF)) %>%
  left_join(df_surg_prf %>% distinct(PRF, REG),
            by = join_by(PRF))
```

# region map

```{r}
p_reg <- map_jp %>%
  ggplot()+
  geom_sf(aes(fill = REG), linewidth = 0.2, alpha = 0.7) +
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                    name = "Region")+
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
 guides(fill =guide_legend(ncol = 2, byrow = FALSE,
                           override.aes = list(alpha = 1, size = 2.8, colour = "black",
                                                 linewidth = 0.1)))+

  theme_void()+
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))

p_reg
```


```{r}
p1_b_new <- p1_b +
  inset_element(p_reg,
                left = 0.4,
                bottom = 0,
                right = 1,
                top = 2/3)

p1_b_new
```


```{r}
p1 <- p1_a1 + 
  p1_a2 + 
  p1_b_new + p1_c1 + p1_c2 +
  p1_d +
  plot_layout(design = "
              AAAAAAAAA
              AAAAAAAAA
              BBBBBBBBB
              BBBBBBBBB
              CCCDDDEEE
              CCCDDDEEE
              CCCDDDEEE
              CCCDDDEEE
              FFFFFFFFF
              FFFFFFFFF
              FFFFFFFFF
              FFFFFFFFF
              FFFFFFFFF
              FFFFFFFFF")

p1

ggsave("../figure/Fig6.pdf", p1, width = 174, height = 234, units = "mm")
```
