---
title: "Pancreatic cacner"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(readxl)
library(openxlsx)
library(openxlsx2)

library(modifiedmk)

library(fpp3)

library(ggtext)
library(patchwork)
library(cowplot)
```


```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
# make df folder

dir.create("../table", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_dem_reg <- readRDS("../rds/surg/dem/df_surg_dem_reg")
```

```{r}
df_surg_prf_reg <- readRDS("../rds/surg/prf/df_surg_prf_reg")
```


```{r}
#df_inj_dem <- readRDS("../df/dem/df_inj_dem_reg")
```

```{r}
df_inc_prf_long <- readRDS("../rds/cancer/df_inc_panc_long.RDS")
```


```{r}
df_surg_dem %>% count(YEAR_str)
```

```{r}
df_surg_dem %>% filter(is.na(TOTAL)) %>% nrow()
```


```{r}
df_surg_dem %>% count(SHEET, YEAR_str)
```


```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K702|^K703")) %>% View()
```

```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K702|^K703")) %>% View()
```

```{r}
 df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K700|^K702|^K703")) %>% count(CLASS_code, CLASS_name)
```


```{r}
# 702 body and tail
# 703 head
# 704 total 全摘

df_panc <- df_surg_dem_reg  %>% 
  filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code %in% c("K700", "K700-4") ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Enucleation")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Enucleation")))
```

```{r}
# get colnames

col_dem <- df_panc  %>%
  select(c(starts_with("M_"), starts_with("F_")) ) %>%
  colnames()

col_dem 
```
```{r}
df_panc <- df_panc %>%
      mutate(across(c(TOTAL,
                    starts_with("M_"),
                    starts_with("F_")), ~ replace_na(.x, "-"))) %>%
    
    mutate(across(c(TOTAL,
                    starts_with("M_"),
                    starts_with("F_")), ~ as.numeric(.x)))
  
```



```{r}
df_panc_2 <- df_panc %>%
    mutate(N_na = rowSums(is.na(across(any_of(col_dem))))) %>%
  mutate(SUM_ori = rowSums(across(any_of(col_dem)), na.rm = TRUE))
```


```{r}
df_panc_2  %>% filter(SUM_ori + N_na * 9 > TOTAL) %>% nrow()

df_panc_2  %>% filter(SUM_ori + N_na * 9 == TOTAL) %>% nrow()

df_panc_2  %>% filter(SUM_ori + N_na * 9 < TOTAL) %>% nrow()
```


```{r}
# 702 body and tail
# 703 head
# 704 total 全摘

df_panc_prf <- df_surg_prf_reg  %>% 
  filter(str_detect(CLASS_code, "K700|^K702|^K703|^K704")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        str_detect(PRO_name, "腹腔鏡") &  str_detect(PRO_name, "手術用支援機器") ~ "Robotic",
                        .default = "Open") ) %>%
  
  
  mutate(LOC = case_when(str_detect(PRO_name, "膵頭") ~ "Head",
                         str_detect(PRO_name, "膵体尾部") ~ "Distal",
                         str_detect(PRO_name, "全摘") ~ "Total",
                         CLASS_code %in% c("K700", "K700-4") ~ "Middle",
                         CLASS_code %in% c("K700-2", "K700-3") ~ "Enucleation")) %>%
  mutate(TX = factor(TX, levels = c("Open", "Lap", "Robotic"))) %>%
  mutate(LOC = factor(LOC, levels = c("Head", "Distal", "Total", "Middle", "Enucleation")))
```

```{r}
# get colnames

col_prf <- df_panc_prf  %>%
  select(c(starts_with("M_"), starts_with("F_")) ) %>%
  colnames()

col_dem 
```

```{r}
df_panc_prf <- df_panc_prf %>%
      mutate(across(c(TOTAL,
                    starts_with("M_"),
                    starts_with("F_")), ~ replace_na(.x, "-"))) %>%
    
    mutate(across(c(TOTAL,
                    starts_with("M_"),
                    starts_with("F_")), ~ as.numeric(.x)))
  
```



```{r}
df_panc_prf_2 <- df_panc_prf %>%
    mutate(N_na = rowSums(is.na(across(any_of(col_dem))))) %>%
  mutate(SUM_ori = rowSums(across(any_of(col_dem)), na.rm = TRUE))
```


```{r}
df_panc_prf_2  %>% filter(SUM_ori + N_na * 9 > TOTAL) %>% nrow()

df_panc_prf_2  %>% filter(SUM_ori + N_na * 9 == TOTAL) %>% nrow()

df_panc_prf_2  %>% filter(SUM_ori + N_na * 9 < TOTAL) %>% nrow()
```
